### ISSUE TITLE
WebNowPlaying plugin out of date.

### ISSUE THREAD

**Issue by tjhrulz** [redsaph/cleartext#1]
Hey redsaph I just pushed an update for the chrome & firefox extensions of WebNowPlaying. While not required a few sites may not always work without the updated plugin. Also this removes the spotify API since I was able to work around it thanks to some new changes in spotify's website which should fix a potential crash some had on really locked down networks.

In the future there should be very little plugin updates required, but because of the API changes and I was a little too aggressive at ignoring media sources sometimes there was no way for me to just make changes in the autoupdating companion extension.

https://github.com/tjhrulz/WebNowPlaying/releases

**Comment by tjhrulz** [comment]
Also you may wish to point your link to the issue of the firefox plugin to point to https://github.com/tjhrulz/WebNowPlaying-BrowserExtension/issues/7 since I merged the two plugins codebases when I did the rewrite.

**Comment by redsaph** [comment]
@tjhrulz No problem! I'll work on an update bundling the latest version of your plugin with Cleartext and the link for my website. Huge thanks 👍
