### ISSUE TITLE
Amazon Music WebNowPlaying

### ISSUE THREAD

**Issue by jondiaz1985** [redsaph/cleartext#16]
I have this submitted on the WebNowPlaying extension also. With Amazon Music playing through a website, neither the information or the controls work anymore. This started around late October when Amazon switched their web format a little. I'm not sure if it's the extension or how the extension is talking to the skin. I find the web version of Amazon Music to be much more enjoyable and easy to use so I generally stick with that.

**Comment by redsaph** [comment]
Hi @jondiaz1985, this is an issue with WebNowPlaying. If there is any changes to the plugin, I will be sure to update Cleartext. For now there is nothing I can do.
