### ISSUE TITLE
song progress not working

### ISSUE THREAD

**Issue by goobths** [redsaph/cleartext#18]
the song progress on spotify stays at 00:00 and 0%

**Comment by jrkmtf** [comment]
Having the same issue. Did you ever find a fix?

**Comment by jrkmtf** [comment]
> Having the same issue. Did you ever find a fix?

Neverming - I figured it out. If you're still having the problem, you need to change the Player from Spotify to WebNowPlaying and use spicetify-cli to enable the webnowplaying extension. I had tried this and at first it wasn't even retrieving song info from Spotify but after about 10 seconds it finally pulled the data in and properly displayed song and progress info.

https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user

**Comment by redsaph** [comment]
Yup, I have also outlined the same [on my wiki entry](https://github.com/redsaph/cleartext/wiki/Support#spotify-and-rainmeter). Thanks @jrkmtf for responding to him!
