### ISSUE TITLE
Song progress and Webplaying are faulty

### ISSUE THREAD

**Issue by Bunny5942** [redsaph/cleartext#19]
it isn't able to detect track progress and there isn't any option to remove it(As I type this I realized I can just alter its setting file but come on, you've made a classy settings panel for it).

As for the Chrome extension, It's just missing... shows error 404 from the given link and turns up nothing upon manual search.

hope you can fix these or atleast provide with a workaround, thank you.

**Comment by sctanf** [comment]
This is a WNP issue, not Cleartext. Please open an issue on the WNP GitHub instead. I believe a new version of the WNP plugin is being worked on. For now you will have to manually install it.
