### ISSUE TITLE
Custom Colors

### ISSUE THREAD

**Issue by mendel3** [redsaph/cleartext#5]
Is there a way to customize the color of Cleartext, other than black and white?
Thanks!

**Comment by redsaph** [comment]
@mendel3 Hi there! The best way to customize Cleartext's colors is by manually modifying the `color.inc` file. More information about color changing can be found [here](http://redsaph.xyz/support/general/cleartext/42/).

**Comment by redsaph** [comment]
Instead of modifying the `color.inc` file, the colors can be modified in the Settings panel in version 6.0.
