### ISSUE TITLE
Long track or author titles ruin skin horizontal values

### ISSUE THREAD

**Issue by cherryleafroad** [redsaph/cleartext#6]
If you have a too long track or author text, then it ruins the skin. It will push the skin all the way off the screen (you'll have to turn off keep on screen), then you can't retrieve it without setting high negative X position values. Refreshing / unloading / loading / changing to a track with a shorter title does not fix the problem. 

Additionally, after the bug occurs, there's an invisible horizontal border where anything within that X value's width by which the skin extends cannot be selected / used (like clicking on a desktop icon).

Upon further analysis, these variables get saved to `variables.inc` :
```
lastSetWidth=1385
nowTextPositionHor=1452.5
hairlinePositionHor=1439
topTextPositionHor=1425.5
playCtrlPositionHor=1490.75
settingsTextPositionHor=1486.25
indicatorPositionHor=1504.25

conflictIndicatorPositionHor=1479.5
```

Manually resetting these to 0 seems to fix it until the next time it happens.

Recommended solution:
- Fix formulas which are causing extraordinarily high values / not resetting them when the text is smaller.
- Implement some kind of text cutoff / text scroll, configurable inside the settings, similar to what you have on the Pure version.

![image](https://user-images.githubusercontent.com/13651622/75617447-ffa91a00-5b13-11ea-864d-3ad984f5415e.png)

**Comment by redsaph** [comment]
Thanks for this @cherryleafroad! The new 6.0 update brings scrolling on regular Cleartext which should avoid this.
