### ISSUE TITLE
Song length is always at 00:00/00:00 and 0%.

### ISSUE THREAD

**Issue by Lighwan** [redsaph/cleartext#7]

**Comment by redsaph** [comment]
Hi, which player is this occurring with?

**Comment by Lighwan** [comment]
Cleartext 6.0 connected to spotify. 
![kuva](https://user-images.githubusercontent.com/68567124/88166059-5926f800-cc1f-11ea-876f-23b05f5657c9.png)

**Comment by redsaph** [comment]
If you're using the Spotify (Now Playing) option, this is expected. I suggest you use WebNowPlaying and Spicetify. [Please refer to this guide on configuring them. ](https://github.com/marcopixel/Monstercat-Visualizer/wiki/WebNowPlaying-Spotify)
