### ISSUE TITLE
Song title not showing

### ISSUE THREAD

**Issue by Lighwan** [redsaph/cleartext#8]
If you disable scrolling and align Cleartext onto the right, long titles occasionally dissappear

**Comment by redsaph** [comment]
Hi, with which player is this occurring? What other modifications were done with Cleartext? How do you replicate the issue?

**Comment by Lighwan** [comment]
Player is cleartext (not cleartext pure) with spotify. Only modifications made were aligning the player onto the right and disabling scrolling.

I then played a piece of music with this title: Sarasate: Introduction et Tarantelle, Op 43. That made the song title completely dissappear and only show the authors name.

**Comment by Lighwan** [comment]
Here are pictures for the bug happening on the right but not on the left.
![kuva](https://user-images.githubusercontent.com/68567124/88165917-1bc26a80-cc1f-11ea-8eb3-f69fcf04e06d.png)

![kuva](https://user-images.githubusercontent.com/68567124/88165948-28df5980-cc1f-11ea-8be5-a90ec94dd8f1.png)

**Comment by redsaph** [comment]
I'll try to replicate that and see what I can do. :)

**Comment by pradeepjts** [comment]
Hi, I want to replace Windows Media Player with Groove Music, Or else I want to add Groove Music. Where can I change the code for this?

**Comment by IsAvaible** [comment]
I'm running into this issue too. Any news?
